$(document).ready(function(){wrap_DmVideoVs()});function wrap_DmVideoVs(){DmVideoGl.setPreVals();DmVideoVs.startMethod()}
var mapViCanPlay=new Map,mapViTimeUpdate=new Map,isAddingPlViRecord=!1,DmVideoGl=function(b){b.setPreVals=function(){var a=location.href;a&&-1!=a.indexOf("videoUrl=")&&-1!=a.indexOf("title=")&&-1!=a.indexOf("poster=")&&($("#pa_videoWi").val(document.body.clientWidth),$("#pa_videoHi").val(document.body.clientHeight),a=DmVideoVs.getSubRiSec(a,"?"),$("#pa_id").val(a.substring(a.indexOf("id=")+3,a.indexOf("&"))),a=DmVideoVs.getSubRiSec(a,"&"),$("#title").text("Yoo\u89c6\u9891\u76f4\u8fde-"+a.substring(a.indexOf("title=")+
6,a.indexOf("&"))),a=DmVideoVs.getSubRiSec(a,"&"),$("#pa_poster").val(a.substring(a.indexOf("poster=")+7,a.indexOf("&"))),a=DmVideoVs.getSubRiSec(a,"&"),$("#pa_url").val(a.substring(a.indexOf("videoUrl=")+9,a.length)))};b.getVideoWi=function(){var a="",c=$("#pa_videoWi");c&&0<c.length&&c.val()&&(a=1*c.val());return a};b.getVideoHi=function(){var a="",c=$("#pa_videoHi");c&&0<c.length&&c.val()&&(a=1*c.val());return a};b.getCleanUrl=function(a){var c="";return c=-1!=a.indexOf("?")?a.substring(0,a.indexOf("?")):
a};return b}(window.DmVideoGl||{}),DmVideoGlInp=function(b){b.ckIsCanPlay=function(a,c,b){a=getActionByHz("action/hySe/prHyUserVi/ckIsCanPlayAjax?id="+a+"&daType=jsonp");$.ajax({url:a,type:"get",dataType:"jsonp",jsonpCallback:"jpc",success:function(a){c&&c(a)},error:function(a){b&&b(a)}})};b.addHyPlayViRecord=function(a,c,b){var e=getActionByHz("action/hySe/prHyUserVi/addPlayViRecordAjax?id="+a+"&daType=jsonp");$.ajax({url:e,type:"get",dataType:"jsonp",jsonpCallback:"jpc",success:function(a){c&&c(a)},
error:function(c){b&&b(c,a)}})};return b}(window.DmVideoGlInp||{}),DmVideoVs=function(b){b.startMethod=function(){b.startClSinVideo()};b.getSubRiSec=function(a,c){return a.substring(a.indexOf(c)+1,a.length)};b.startClSinVideo=function(){var a=$.trim($("#pa_id").val()),c=$.trim($("#pa_url").val()),f=$.trim($("#pa_videoWi").val()),e=$.trim($("#pa_videoHi").val()),g=$.trim($("#pa_poster").val()),h=browser.platform.mobile,d=DmVideoGl.getCleanUrl(c),k=Storage.getItem(d+"_poster"),d=Storage.getItem(d+"_viHeight"),
f=f?f:h?b.getMobileViWiSec():380,f="width:"+(-1!=(f+"").indexOf("%")?f+";":f+"px;"),e=e?e:h?b.getMobileViHiSec(d):492,e="height:"+(-1!=(e+"").indexOf("%")?e+";":e+"px;"),g=k?k:g,a=""+(" <video "+(g?"poster="+g:"")+' id="yooVideo" vi-id="'+a+'" style="'+f+e+'" class="" playsinline  loop controls>\n')+('  <source src="'+c+'" type="video/mp4" />\n'),a=a+" </video>\n";$("body").append(a);a=$("#yooVideo");c=b.startBindMp("yooVideo",a);g||c.load();return a};b.startBindMp=function(a,c){return c.mediaelementplayer({playText:"\u70b9\u51fb\u8fdb\u884c\u64ad\u653e",
iceFullScreenMod:"wefs",pauseOtherPlayers:browser.platform.iPhone?!0:!1,success:function(a){a.addEventListener("play",function(a){var c=a.target,b=$(c).find("video");a=b.attr("vi-id");$(b).attr("autobuffer","autobuffer");if(a&&"undefined"!=a){var d=1*a,b=mapViCanPlay.get(d);(d=mapViTimeUpdate.get(d))&&d.stTime&&(d.stTime=new Date);void 0!=b?b.isSuccess||(c.pause(),alertVipLiSmPop("\u7acb\u5373\u5145\u503c",b.msg)):DmVideoGlInp.ckIsCanPlay(a,function(a){var b=a.isSuccess;mapViCanPlay.put(a.prHyUserViId,
{msg:a.messageContent,isSuccess:b});b||(c.pause(),"mustCz"==a.messageCode&&alertVipLiSmPop("\u7acb\u5373\u5145\u503c",a.messageContent))},function(){})}},!1);a.addEventListener("timeupdate",function(a){var b=$(a.target).find("video");a=1*b.attr("vi-id");b=(b=b[0])&&b.currentTime;if(mapViTimeUpdate.get(a)){var c=mapViTimeUpdate.get(a),d=c.stPlTime;10<calcDateChaSeconds(c.stTime,new Date)&&b!=d&&!isAddingPlViRecord&&!c.isRqAddedRecord&&(isAddingPlViRecord=!0,DmVideoGlInp.addHyPlayViRecord(a,function(a){isAddingPlViRecord=
!1;var b=a.isSuccess,c=mapViTimeUpdate.get(a.prHyUserViId);c.isRqAddedRecord||(c.isRqAddedRecord=!0);b||console.error(a.messageContent)},function(a,b){isAddingPlViRecord=!1;var c=mapViTimeUpdate.get(b);c.isRqAddedRecord||(c.isRqAddedRecord=!0)}))}else mapViTimeUpdate.put(a,{stTime:new Date,stPlTime:b,isRqAddedRecord:!1})},!1)},error:function(a){console.error(a)}})};b.getMobileViWiSec=function(){if(browser.platform.mobile)return"100%"};b.getMobileViHiSec=function(a){if(browser.platform.mobile)return a?
a:document.body.clientHeight};return b}(window.DmVideoVs||{});
